name: Build Storybook
on:
  pull_request:
    types: 
      - closed
    branches: 
    - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo code
        uses: actions/checkout@v3
      - name: Build Storybook
        run: pnpm run build-storybook
      - name: Finished
        run: echo "Build Finished"
