name: Build Storybook
on:
  pull_request:
    types: 
      - closed
    branches: 
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build Storybook
        run: npm run build-storybook
      - name: Upload Static Storybook artifact
        uses: actions/upload-artifact@v3
        with:
          name: Static Storybook
          path: storybook-static
      - name: Finished
        run: echo "Build Finished"
